#!/bin/sh

##
# This script verifies permission to write to the log file, prompts for sudo if permission if that is needed.
# Then it sets up ./wdog to run ./webserv and keep it alive.
##

REAL=`realpath $0`
cd `dirname $REAL`
NAME=`basename $PWD`
if [ -w ../../log ] ; then
	./wdog ./$NAME  "$*" >> ../../log/$NAME.log 2>> ../../log/$NAME.log &
	exit 0
fi
if [ -w / ]; then
	echo "Could not create log file: ../../$NAME.log" >&2
	exit 1
fi
sudo /700s/sys/env "./start" "$*"
exit $?
