#!/sbin/sh
#
# $NetBSD: mysqld.sh,v 1.1 2016/09/16 06:49:12 adam Exp $
#
# Init script for mysqld.
#

UMASK=0640; UMASK_DIR=0750 # added by us

. /lib/svc/share/smf_include.sh

PIDFILE="/700s/db/mysql.pid"

ulimit -n 10240

case "$1" in
start)
	/opt/local/sbin/mysqld --user=mysql \
		--basedir=/opt/local \
		--datadir=/700s/db \
		--pid-file=${PIDFILE} \
		--log-error=/700s/log/mysql-error.log &
	;;
stop)
	[ -f ${PIDFILE} ] && kill `/usr/bin/head -1 ${PIDFILE}`
	;;
*)
	echo "Usage: $0 {start|stop}" >&2
	exit 1
	;;
esac

exit $SMF_EXIT_OK
